- name: Insights PLaybook
  hosts: tag_ansible_group_stig 
  gather_facts: yes 
  vars:
    insights_display_name: "{{ inventory_hostname }}"
  roles:
    - { role: redhataccess.redhat-access-insights-client, when: ansible_os_family == 'RedHat' }
      #when: ansible_os_family == 'RedHat'
