- name: STIG RHEL 7 profile configuration
  hosts: tag_ansible_group_stig,meta-tag_ansible_group_stig,foreman_hostgroup_demo 
  become: true

  #roles:
  #  - role: RHEL7-STIG
  #    when:
  #      - ansible_os_family == 'RedHat'
  #      - ansible_distribution_major_version | version_compare('7', '=')

  tasks:
    - name: Extra Controls not implemented with the STIG content 
      debug:
        msg: "Tasks for applying additonal content"


