- hosts: tag_ansible_group_stig, meta-tag_ansible_group_stig
  roles:
    - role: RHEL7-STIG
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | version_compare('7', '=')
