# from GitHub
- src: https://github.com/redhataccess/ansible-redhat-access-insights-client.git
  scm: git

#- src: https://github.com/MindPointGroup/RHEL7-CIS.git
# ansible-galaxy install -p roles -r requirements.yml
