---
# tasks/audit_command.yml

- name: "MEDIUM | RHEL-07-{{ item.id }} | {{ item.create | ternary('PATCH', 'REVERT') }} | All uses of the {{ item.path | basename }} command must be audited."
  lineinfile:
    path: "/etc/audit/rules.d/rhel7stig_commands.rules"
    create: yes
    owner: root
    group: root
    mode: 0600
    line: "-w {{ item.path }} -p x -F auid!=4294967295 -k {{ item.key }}"
    state: "{{ item.create | ternary('present', 'absent') }}"
  notify: restart auditd
