---
# tasks/audit_system_call.yml

- name: "MEDIUM | RHEL-07-{{ item.id }} | {{ item.create | ternary('PATCH', 'REVERT') }} | All uses of the {% if item.call is defined %}{{ item.call }}{% elif item.path is defined %}{{item.path | basename}}{% endif %} command must be audited."
  lineinfile:
    path: "/etc/audit/rules.d/rhel7stig_system_calls.rules"
    create: yes
    owner: root
    group: root
    mode: 0600
    line: "-a always,exit -F arch=b64 {% if item.call is defined %}-S {{ item.call }}{% elif item.path is defined %}-F path={{item.path}}{% endif %} {{ item.extra_fields | default('') }} {%if item.include_all_auids is defined %}{% else %}-F auid>=1000 -F auid!=4294967295{% endif %} -k {{ item.key }}"
    state: "{{ item.create | ternary('present', 'absent') }}"
  notify: restart auditd
