- name: "LOW | RHEL-07-020200 | PATCH | The operating system must remove all software components after updated versions have been installed."
  lineinfile:
      dest: /etc/yum.conf
      regexp: ^#?clean_requirements_on_remove
      line: clean_requirements_on_remove=1
      insertafter: '\[main\]'
  when: rhel_07_020200
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-020200

- name: "LOW | RHEL-07-020300 | PATCH | All Group Identifiers (GIDs) referenced in the /etc/passwd file must be defined in the /etc/group file."
  block:
      - name: "LOW | RHEL-07-020300 | PATCH | Check /etc/passwd entries"
        shell: pwck -r | grep 'no group' | awk '{ gsub("[:\47]",""); print $2}'
        changed_when: no
        failed_when: no
        register: passwd_gid_check

      - name: "LOW | RHEL-07-020300 | PATCH | Print warning about users with invalid GIDs missing GID entries in /etc/group"
        debug:
            msg: "WARNING: The following users have non-existent GIDs: {{ passwd_gid_check.stdout_lines | join (', ')}}"
        when: passwd_gid_check.stdout_lines
  when: rhel_07_020300
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-020300
      - passwd

- name: "LOW | RHEL-07-021310 | PATCH | A separate file system must be used for user home directories (such as /home or an equivalent)."
  debug:
      msg: "WARNING: /home is not mounted on a separate partition"
  when:
    - rhel_07_021310
    - ansible_mounts | selectattr('mount', 'match', '^/home$') | list | length == 0
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-021310
      - mount
      - home

- name: "LOW | RHEL-07-021320 | PATCH | The system must use a separate file system for /var."
  debug:
      msg: "WARNING: /var is not mounted on a separate partition"
  when:
    - rhel_07_021320
    - ansible_mounts | selectattr('mount', 'match', '^/var$') | list | length == 0
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-021320
      - mount
      - var

- name: "LOW | RHEL-07-021330 | PATCH | The system must use a separate file system for the system audit data path."
  debug:
      msg: "WARNING: /var/log/audit is not mounted on a separate partition"
  when:
    - rhel_07_021330
    - ansible_mounts | selectattr('mount', 'match', '^/var/log/audit$') | list | length == 0
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-021330
      - mount
      - auditd

- name: "LOW | RHEL-07-021340 | PATCH | The system must use a separate file system for /tmp (or equivalent)."
  systemd:
      name: tmp.mount
      daemon_reload: yes
      enabled: yes
      masked: no
      state: started
  when: rhel_07_021340
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-021340
      - mount
      - tmp

- name: "LOW | RHEL-07-021600 | PATCH | The file integrity tool must be configured to verify Access Control Lists (ACLs)."
  command: "true"
  changed_when: no
  when: rhel_07_021600
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-021600
      - notimplemented

- name: "LOW | RHEL-07-021610 | PATCH | The file integrity tool must be configured to verify extended attributes."
  command: "true"
  changed_when: no
  when: rhel_07_021610
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-021610
      - notimplemented

- name: "LOW | RHEL-07-040000 | PATCH | The operating system must limit the number of concurrent sessions to 10 for all accounts and/or account types."
  lineinfile:
    state: present
    dest: /etc/security/limits.conf
    insertbefore: '^# End of file'
    regexp: '^#?\\*.*maxlogins'
    line: '*           hard    maxlogins     {{ rhel7stig_maxlogins }}'
  when: rhel_07_040000
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-040000

- name: "LOW | RHEL-07-040530 | PATCH | The system must display the date and time of the last successful account logon upon logon."
  blockinfile:
    state: present
    path: /etc/pam.d/postlogin
    insertafter: '^# User changes will be destroyed'
    block: |
        ### RHEL-07-040530 ###
        session required pam_lastlog.so showfailed
  when: rhel_07_040530
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-040530

- name: "LOW | RHEL-07-040600 | PATCH | For systems using DNS resolution, at least two name servers must be configured."
  command: "true"
  changed_when: no
  when: rhel_07_040600
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-040600
      - notimplemented

